apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4= # base64-encoded value of "admin"
  password: cGFzc3dvcmQ= # base64-encoded value of "password"

---

apiVersion: v1 
kind: ConfigMap
metadata:
  name: my-config
data:
  key: name
  value: Shiv Pratap Verma
