apiVersion: v1
kind: Pod
metadata:
  name: pod-rediness
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 5000
      readinessProbe:
        httpGet:
          path: /api/ready
          port: 5000
        initalDelaySeconds: 10
