apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ui-deploy-
spec:
  serviceAccountName: quay-login
  pipelineRef:
    name: ui-pipeline
  params:
    - name: IMAGE
      value: quay.io/pratap0007/xy
    - name: TAG
      value: v1
    - name: HUB_NAMESPACE
      value: tekton-hub
    - name: K8S_VARIANT #it will accept either openshift or kubernetes
      value: kubernetes
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
