apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
    - name: alpine
      image: alpine
      command: ['/bin/sh', '-c']
      volumeMounts:
        mountPath: /opt
        name: data-volume
      volumes:
        name: data-volume
        persistentVolumeClaim:
          claimName: myclaim
