apiVersion: v1
kind: Pod
metadata:
  name: pod-valume
spec:
  containers:
    - name: alpine
      image: alpine
      command: ['/bin/sh', '-c']
      args: ['shuff -i 0-100 -n 1 >> /opt/number.out;']
