apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: multiple-echo
spec:
  steps:
    - name: step-1
      image: ubuntu
      command:
        - echo
      args:
        - 'a'
        - 'b'
        - 'c'
        - 'd'
