apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  steps:
    - name: goodbye
      image: ubuntu
      script: |
        #!/bin/bash
        sleep 30
        echo "Goodbye World!"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: hello
      image: ubuntu
      script: |
        #!/bin/bash
        sleep 35
        echo "Goodbye World!"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: again
spec:
  steps:
    - name: again
      image: ubuntu
      script: |
        #!/bin/bash
        sleep 40
        echo "Goodbye World!"
