apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match te spec field below, and be in the form of <plural>.<group>
  name: myclinics.abc.com
spec:
  # grout name to use for rest api : /apis/<group>/<version>
  group: abc.com
  names:
    # plural name to be used in the url /api/group/version/plural
    plural: myclinics
    # singular name to be used as an alias on the cli and for display
    singular: myclinic
    kind: MyClinic
    # short name allow shorter to match your resource on the cli
    shortNames:
      - myc
  # either namespaces or cluster
  scope: Namespaced
  versions:
    - name: v1alpha1
      # each version can be enabled or diabled by served flag.
      served: true
      # one and only one version must be makked as the storage version
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                patentName:
                  type: string
                address:
                  type: string
                disease:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
