apiVersion: batch/v1
kind: Job
metadata:
  name: processing-job
spec:
  template:
    spec:
      containers:
        - name: add-job
          image: ubuntu
          command: ['expr', '3', '+', '2']
      restartPolicy: Never
