apiVersion: v1
kind: Pod
metadata:
  name: resource-req
spec:
  containers:
    - name: nginx-res-req
      image: nginx
      ports:
        - containerPort: 4000
      resources:
        requests:
          memory: '1Gi'
          cpu: 1
        limits:
          memory: '2Gi'
          cpu: 2
