apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: task1 
spec:
  steps:
    - name: task1-step
      image: ubuntu
      # image: registry.redhat.io/ubi8/ubi-minimal@sha256:6910799b75ad41f00891978575a0d955be2f800c51b955af73926e7ab59a41c3 
      script: |
        #!/bin/bash
        echo "hello task1"

