apiVersion: v1
kind: Pod
metadata:
  name: simple-app
  labels:
    app: ui-app
    function: cra
spec:
  containers:
    - name: simple-webapp
      image: nginx
      ports:
        - containerPort: 4000
