apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  labels:
    app: deployment-app
spec:
  template:
    metadata:
      name: abc
      labels:
        app: deployment-app
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      app: deployment-app
