apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: goodbye
spec:
  steps:
    - name: goodbye
      image: ubuntu
      script: |
        #!/bin/bash
        sleep 3000
        echo "Goodbye World!"

