apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: again
spec:
  steps:
    - name: again
      image: ubuntu
      script: |
        #!/bin/bash
        sleep 40
        echo "Goodbye World!"
  params:
    - name: url
      description: name of the url
      type: string
