apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simple-task-1
spec:
  # params:
  steps:
    - name: echo
      image: ubuntu
      command:
        - /bin/bash
      args: ['-c', 'echo hello world']
