apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: hello-clustertask
spec:
  workspaces:
    - name: abc
      optional: true
    - name: xyz
  steps:
    - name: step-1
      image: alpine
      script: |
        #! /bin/bash
        echo "hello clustertask"
