
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /mnt/data
      containers:
      - name: container-1-nginx
        image: nginx
        volumeMounts:
          - name: vol 
            mountPath: "/var/nginx-data"
      - name: container-2-tomcat
        image: tomcat
